version: "3"
services:
  redis_server:
    image: redis
  zookeeper:
    image: 'bitnami/zookeeper:3'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  db:
    image: mysql:5.7
    ports:
    - 3307:3306
    volumes:
      - db_data_url_short:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: url_short
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  app:
    build: .
    environment:
      DB_HOST: db:3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: url_short
      ZOOKEEPER_URL: zookeeper:2181
      REDIS_URL: redis_server
      REDIS_PORT: 6379
    ports:
      - 5000:80
    links:
      - redis_server:redis_server
      - zookeeper:zookeeper
    depends_on:
      - db
      - zookeeper
      - redis_server

volumes:
    db_data_url_short:
